# Generated by Django 4.0.4 on 2024-10-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
